### ISSUE TITLE
Multiple browsers

### ISSUE THREAD

**Issue by enk21** [jlesage/docker-firefox#130] opened 2022-08-26 06:46 UTC
Is it possible to have a new browser session each time the url is called? Currently, if I open another browser, they both display the same browser session. Thanks

**Comment by emiguerol** [comment] 2022-08-27 17:03
+1

**Comment by jlesage** [comment] 2022-08-28 23:57
The container is running a single instance of Firefox.  So when you connect from multiple browsers, you are accessing the same instance.

If you want/need multiple Firefox instances, you need to have multiple instances of the container.  Just make sure that for each instance, port 5800 is mapped to a different port of the host.

**Comment by ha-8d3b05** [comment] 2023-04-06 09:54
and most important for each firefox instance make a different /docker/appdata/firefox

**Comment by yamikeigo** [comment] 2024-12-29 09:33
> and most important for each firefox instance make a different /docker/appdata/firefox

this might be the piece i'm missing. I'm currently getting the following from my 3rd instance in the same stack:

![lesage_ff1](https://github.com/user-attachments/assets/d66ade7a-4ad0-4af5-970c-b38d0627b9ce)

where do I place file path? I don't see it anywhere in the config folder on the host or within the container itself

any thoughts @jlesage ?

**Comment by yamikeigo** [comment] 2024-12-29 09:40
> The container is running a single instance of Firefox. So when you connect from multiple browsers, you are accessing the same instance.
> 
> If you want/need multiple Firefox instances, you need to have multiple instances of the container. Just make sure that for each instance, port 5800 is mapped to a different port of the host.

please feel free to correct me, because I may be totally doing things wrong, but I think this is not entirely accurate...

yes the host port needs to be changed, but that also means they have to be on separate networks. Unless we can change the internal container port, but I believe that's baked into the image itself

so if in the same stack, this means each container has to be on separate networks from each other so that each container port will remain XXXX:5800

**Comment by jlesage** [comment] 2024-12-29 13:59
Each instance must:
- Have the /config folder mapped to a different host folder/volume.
- Have port 5800 mapped to a different port on the host.

When using the default bridge network,the port inside the container is always the same, but it is mapped to a different port on the host side. No need to create and use different networks.

**Comment by yamikeigo** [comment] 2024-12-29 20:12
> Each instance must:
> 
>     * Have the /config folder mapped to a different host folder/volume.
> 
>     * Have port 5800 mapped to a different port on the host.
> 
> 
> When using the default bridge network,the port inside the container is always the same, but it is mapped to a different port on the host side. No need to create and use different networks.

ok yeah you're right. perhaps it was something else that glitched out my container and then I jumped to the conclusion that it was the port. all working as intended from one network in the stack. thanks for your timely responses. all my issues solved

**Comment by jlesage** [comment] 2024-12-29 23:19
Great ! Closing this issue. If someone else has an issue please re-open.

**Closed by jlesage** 2024-12-29 23:19 UTC
